jQuery(function($){if(typeof wc_add_to_cart_params==='undefined')
return false;$(document).on('click','.add_to_cart_button',function(){var $thisbutton=$(this);if($thisbutton.is('.product_type_simple')){if(!$thisbutton.attr('data-product_id'))
return true;$('.notification').removeClass('showed');$thisbutton.removeClass('added');$thisbutton.addClass('loading');var data={action:'woocommerce_add_to_cart',product_id:$thisbutton.attr('data-product_id'),quantity:$thisbutton.attr('data-quantity')};$('body').trigger('adding_to_cart',[$thisbutton,data]);$.post(wc_add_to_cart_params.ajax_url,data,function(response){if(!response)
return;var this_page=window.location.toString();this_page=this_page.replace('add-to-cart','added-to-cart');if(response.error&&response.product_url){window.location=response.product_url;return;}
if(wc_add_to_cart_params.cart_redirect_after_add==='yes'){window.location=wc_add_to_cart_params.cart_url;return;}else{$thisbutton.removeClass('loading');fragments=response.fragments;cart_hash=response.cart_hash;if(fragments){$.each(fragments,function(key,value){$(key).addClass('updating');});}
$('.shop_table.cart, .updating, .cart_totals').fadeTo('400','0.6').block({message:null,overlayCSS:{background:'transparent url('+ wc_add_to_cart_params.ajax_loader_url+') no-repeat center',backgroundSize:'16px 16px',opacity:0.6}});$thisbutton.addClass('added');if(!wc_add_to_cart_params.is_cart&&$thisbutton.parent().find('.added_to_cart').size()===0){$thisbutton.after(' <a href="'+ wc_add_to_cart_params.cart_url+'" class="added_to_cart wc-forward" title="'+
wc_add_to_cart_params.i18n_view_cart+'">'+ wc_add_to_cart_params.i18n_view_cart+'</a>');}
if(fragments){$.each(fragments,function(key,value){$(key).replaceWith(value);});}
$('.widget_shopping_cart, .updating').stop(true).css('opacity','1').unblock();$('.shop_table.cart').load(this_page+' .shop_table.cart:eq(0) > *',function(){$('div.quantity:not(.buttons_added), td.quantity:not(.buttons_added)').addClass('buttons_added').append('<input type="button" value="+" id="add1" class="plus" />').prepend('<input type="button" value="-" id="minus1" class="minus" />');$('.shop_table.cart').stop(true).css('opacity','1').unblock();$('body').trigger('cart_page_refreshed');});$('.cart_totals').load(this_page+' .cart_totals:eq(0) > *',function(){$('.cart_totals').stop(true).css('opacity','1').unblock();});$('body').trigger('added_to_cart',[fragments,cart_hash]);var text=$thisbutton.parent().parent().find('h3').text();var product_id=$thisbutton.attr("data-product_id");var randomClass="";var possible="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";for(var i=0;i<3;i++){randomClass+=possible.charAt(Math.floor(Math.random()*possible.length));}
$('#main-notif').prepend('<div class="animated fadeInDown maha-notif-cart notif-pid-'+product_id+ randomClass+'"><span>"'+text+'"</span> was successfully added to your cart.</div>');$('.notif-pid-'+product_id+randomClass).hide().fadeIn(700).delay(2000).fadeTo(700,0);setTimeout(function(){$('.notif-pid-'+product_id+randomClass).removeClass('animated fadeInDown').addClass('animated fadeOutRight');setTimeout(function(){$('.notif-pid-'+product_id+randomClass).remove();},500);},3400);}});return false;}
return true;});});